baseURL = '/'
languageCode = 'en-us'
title = 'Nog Pilot'

[markup.goldmark.renderer]
  unsafe = true

[minify.tdewolff.html]
  keepComments = true

[params]
  nogGithubOwner = 'mcsadmin'
  nogGithubRepo = 'nog-pilot'
  nogFormName = 'nog-comment'
